;;----------------------------------------------------------------------
;; Layer 12: unsigned 32-bit arithmetic
;;
;; The bitwise-* family operates on vxs fixnums, which are SIGNED 32-bit:
;;   (bitwise-xor 2147483648 1)  => -2147483647
;;   (arithmetic-shift 1 31)     => -2147483648
;; Defensible for two's-complement integers, and useless for anything
;; that must match a published bit-exact specification — a counter-based
;; RNG, a hash, a checksum. The u32 family takes any number (negative
;; fixnums read as two's complement, flonums wrapped into range) and
;; returns an EXACT unsigned result: a fixnum below 2^31, a flonum above
;; it, since every u32 fits a double's 53-bit mantissa exactly. So they
;; compose — the output of one feeds the next without leaking a sign.
;;
;; Every expected value here was generated by an independent Python
;; implementation, not computed by hand. Two of the first hand-written
;; ones were wrong, which is the argument for doing it this way: a test
;; whose expectations you derived the same way you derived the code
;; proves only that you were consistent.
;;----------------------------------------------------------------------

(load "testcases/test_framework.scm")

(test-suite "12_u32: unsigned 32-bit arithmetic")

(assert-equal "xor above 2^31 stays unsigned" 2147483649 (u32-xor 2147483648 1))
(assert-equal "shift into the top bit" 2147483648 (u32-shl 1 31))
(assert-equal "-1 is 0xFFFFFFFF" 4294967295 (u32 -1))
(assert-equal "and of two large values" 4294967294 (u32-and 4294967294 4294967295))
(assert-equal "add wraps at 2^32" 0 (u32+ 4294967295 1))
(assert-equal "add wraps past" 4 (u32+ 4294967295 5))
(assert-equal "multiply wraps" 1 (u32* 4294967295 4294967295))
(assert-equal "shl loses the high byte" 3430008 (u32-shr (u32-shl 305419896 8) 8))
(assert-equal "rotl by 0 is identity" 3735928559 (u32-rotl 3735928559 0))
(assert-equal "rotl by 32 is identity" 3735928559 (u32-rotl 3735928559 32))
(assert-equal "rotl by 4" 3940282109 (u32-rotl 3735928559 4))
(assert-equal "rotl by 16 swaps halves" 3203391149 (u32-rotl 3735928559 16))
(assert-equal "rotl round-trips" 3735928559 (u32-rotl (u32-rotl 3735928559 7) 25))
(assert-equal "shl by 32 is zero" 0 (u32-shl 1 32))
(assert-equal "shr by 32 is zero" 0 (u32-shr 4294967295 32))
(assert-equal "shr is logical not arithmetic" 2147483647 (u32-shr 4294967295 1))
(assert-equal "not of zero" 4294967295 (u32-not 0))
(assert-equal "not round-trips" 305419896 (u32-not (u32-not 305419896)))
(assert-equal "or combines halves" 4294967295 (u32-or 4294901760 65535))
(assert-equal "bitwise-or alias exists" 3 (bitwise-or 1 2))

;; Rotation is the operation Threefry is built from, and the one C++ makes
;; easy to write wrongly: `x << 32` is undefined behaviour, so rotl by a
;; multiple of 32 must be special-cased rather than assumed. Checked above
;; at 0 and 32.

;; Composition across the 2^31 boundary, which the signed family cannot do.
(assert-equal "a chain of ops stays exact across 2^31"
              4106028280
              (u32+ (u32-rotl (u32-xor 3735928559 2863311530) 13) 305419896))

;;--- u32 values through text -------------------------------------------
;; Bit-exact specifications are published in hex, so reading and writing
;; u32 values as hex has to work across the whole range — including above
;; 2^31, where the value is a flonum here. Both directions were broken in
;; ways that only showed up past that boundary:
;;
;;   (string->number "ffffffff" 16)   => #f      (decimal promoted; hex did not)
;;   (number->string 4294967295 16)   => "4294967295.0"  (radix IGNORED)
;;
;; The second is the nastier one: it answered in decimal without
;; complaint, so hex output looked plausible until compared with a
;; published vector.

(assert-equal "hex parses below 2^31 as exact" 2147483647
              (string->number "7fffffff" 16))
(assert-equal "hex parses at 2^31" 2147483648 (string->number "80000000" 16))
(assert-equal "hex parses 0xFFFFFFFF" 4294967295 (string->number "ffffffff" 16))
(assert-equal "hex rejects non-digits for its radix" #f
              (string->number "zzz" 16))
(assert-equal "binary radix parses" 255 (string->number "11111111" 2))

(assert-equal "formats above 2^31 in the radix asked for" "ffffffff"
              (number->string 4294967295 16))
(assert-equal "formats a large flonum result" "aaaaaaaa"
              (number->string (u32-xor 4294967295 1431655765) 16))
(assert-equal "formats below 2^31 too" "ff" (number->string 255 16))
(assert-equal "formats zero" "0" (number->string 0 16))
(assert-equal "formats negatives" "-ff" (number->string -255 16))
(assert-equal "binary radix formats" "11111111" (number->string 255 2))

(assert-equal "hex round-trips across the boundary" 4294967295
              (string->number (number->string 4294967295 16) 16))

(suite-summary)
